#!/bin/bash

# Find the PID of the process
pid=$(pgrep 4-to_infinity_and_beyond)

# Check if the process is running
if [ -n "$pid" ]; then
    # If the process is running, terminate it
    kill -TERM "$pid"
    echo "Process 4-to_infinity_and_beyond has been stopped."
else
    echo "Process 4-to_infinity_and_beyond is not running."
fi
