#!/bin/bash

# Check if 4-to-infinity_and_beyond is running
pgrep -f 4-to_infinity_and_beyond >/dev/null 2>&1

if [[ $? -eq 0 ]]; then
  # Find the PID of the running process
  pid=$(pgrep -f 4-to_infinity_and_beyond)

  # Send SIGTERM signal to stop the process gracefully
  kill -TERM "$pid"

  # Wait for the process to exit gracefully
  wait "$pid" 2>/dev/null

  if [[ $? -eq 0 ]]; then
    echo "Terminated"
  else
    # If not terminated gracefully, send SIGKILL as a last resort
    kill -KILL "$pid"
    echo "Forcefully stopped"
  fi
else
  echo "Process not running"
fi
