#!/bin/bash

# Create and write PID to file
echo $$ > /var/run/myscript.pid

# Function to handle SIGTERM signal
trap 'echo "I hate the kill command"; exit 0' SIGTERM

# Function to handle SIGINT signal
trap 'echo "Y U no love me?!"; exit 0' SIGINT

# Function to handle SIGQUIT and SIGTERM signals
trap 'rm -f /var/run/myscript.pid; exit 0' SIGQUIT SIGTERM

# Infinite loop printing message
while true; do
  echo "To infinity and beyond"
  sleep 1
done
